src/components/HomepageFeatures.js
src/components/HomepageFeatures.module.css
src/pages/index.module.css

it has a very cool css gradient that is very cool ,i agree ;) Thanks bestie

Add CSS gradient

---

docs/getting-started/extensions.md

Connect spicetify to webnowplaying.js

Adding configure for webnowplaying.js

---

docs/development/customization.md
docs/faq.md

fix: changed config filename

---

docs/getting-started/advanced-installation.md

Following this development (https://github.com/khanhas/spicetify-cli/issues/1290#issuecomment-1019088269), @zwxi, I now pronouce you the official maintainer of the scoop repository!

docs: changed scoop repository

---

docs/development/custom-apps.md
docs/development/customization.md
docs/development/js-modules.md

Put this together. I think it's got the most basic info needed. The longer code block in the middle can probably be trimmed down; I copied chunks of code from Marketplace. Let me know if you have suggestions or questions that could be addressed.

Add initial take at custom apps development page

---

docs/faq.md

Complements #4, which was missing Linux and MacOS paths.

fix: add linux and macOS paths & grammar fix.

---

docs/development/spicetify-creator/_category_.yaml
docs/development/spicetify-creator/building-and-testing.md
docs/development/spicetify-creator/create-custom-apps.md
docs/development/spicetify-creator/create-extensions.md
docs/development/spicetify-creator/the-basics.md

Added a new category under development with 4 pages for Spicetify Creator.
This is my first time doing proper documentation so if you find things to change, improve, or polish I'll do so.
Related to #22

Docs for Spicetify Creator

---

docs/getting-started/advanced-installation.md

Point to the official buckets (https://github.com/spicetify/spicetify-cli/issues/1290#issuecomment-1062704879)

Update scoop installation instructions

---

docs/faq.md

Since it seems to be happening a lot lately

docs: Add FAQ for `prefs_path` error on Windows

---

docusaurus.config.js
src/components/SwiperCarousel.tsx

- Uses `respectPrefersColorScheme` to apply system theme
- Make use of the Carousel by utilizing Autoplay

feat(UX): several improvements

---

docs/development/custom-apps.md
docs/getting-started.md

I don't think much needs to be changed here?

Change name of marketplace and fix master branch reference

---

docs/getting-started.md

I just saw this as I was browsing, figured I'd go fix it.

Fixed up some word repetition

---

docs/advanced-usage/installation.md

Updates the homebrew install command to use our new tap.

chore(docs): update homebrew command

---

docs/advanced-usage/installation.md

Related to https://github.com/spicetify/spicetify-cli/issues/708

docs(installation): add Winget installation instructions

---

docs/development/api-wrapper/methods/panel.md

Use correct prop name for example

chore(wrapper/panel): use correct prop name

---

docs/advanced-usage/custom-apps.md

I have writen the code to uninstall any custom app installed using spicetify which will be much helpful for the users as I have found various search queries for usintalling custom apps

chore: add uninstall instructions to custom-apps.md

---

docusaurus.config.js
sidebars.js

This will promote the more inquisitive users to read the advanced usage guides as they are important for troubleshooting etc
theoretically resolves #78
Disabling auto-collapse also just makes it easier for devs to look through the dev docs lol

fix: disable auto-collapse & expand advanced usage

---

docs/development/api-wrapper/properties/react-components.md
docs/development/api-wrapper/types/react-component/slider-props.md
sidebars.js

https://github.com/spicetify/spicetify-cli/pull/2466

feat: add info about `Slider` React component

---

docs/development/api-wrapper/functions/color-extractor.md
docs/development/api-wrapper/functions/remove-from-queue.md
docs/development/api-wrapper/methods/player.md
docs/development/api-wrapper/properties/react-components.md
docs/development/api-wrapper/properties/react-hook.md

https://github.com/spicetify/spicetify-cli/pull/2695
idk how i missed all of this

docs(api-wrapper): use `Player.data.item`

---

docs/development/api-wrapper/properties/react-components.md
docs/development/api-wrapper/types/react-component/toggle-props.md
sidebars.js

https://github.com/spicetify/spicetify-cli/pull/2708

feat: add info about `Toggle` React component

---

docs/advanced-usage/installation.md

Should be changed because of https://github.com/spicetify/spicetify-cli/pull/2896

feat: change homebrew install cmd

---

docs/advanced-usage/themes.md

Changed theme name to spiceitfy-lucid

chore: rename better-bloom to spicetify-lucid

---

docs/development/spicetify-creator/building-and-testing.md

Added pnpm to the docs for https://spicetify.app/docs/development/spicetify-creator/building-and-testing

Add pnpm to building-and-testing.md

---

docs/advanced-usage/themes.md

A related theme addition PR can be found [here](https://github.com/spicetify/spicetify-themes/pull/1114)

feat(themes): add Skaytacium/Gruvify theme link

---

docs/advanced-usage/themes.md

I wanted to suggest adding the official Dracula theme.

chore: add dracula theme themes.md

---

docs/development/api-wrapper/functions/color-extractor.md

accidentally named commit wrong but its whatever

docs: add dark_vibrant to code block

---

docs/advanced-usage/extensions.md

fix: small typo in extensions.md
